name = "bonyan-api"
main = "src/worker.ts"
compatibility_date = "2026-10-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = true

[[routes]]
pattern = "api.bonyanoss.org"
custom_domain = true

[previews]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BonyanApiContainer"]

[[migrations]]
tag = "v2"
deleted_classes = ["BonyanApiContainer"]
