/*
 * Bonyan-API – Quran & Azkar API
 * Copyright (c) 2026 BonyanOSS
 * MIT License
 */

// Quran.com chapter metadata, retrieved 2026-10-04. See SOURCES.md.
export const SURAH_METADATA = [
    {
        id: 1,
        name: 'الفاتحة',
        makkia: true,
        ayahCount: 7,
    },
    {
        id: 2,
        name: 'البقرة',
        makkia: false,
        ayahCount: 286,
    },
    {
        id: 3,
        name: 'آل عمران',
        makkia: false,
        ayahCount: 200,
    },
    {
        id: 4,
        name: 'النساء',
        makkia: false,
        ayahCount: 176,
    },
    {
        id: 5,
        name: 'المائدة',
        makkia: false,
        ayahCount: 120,
    },
    {
        id: 6,
        name: 'الأنعام',
        makkia: true,
        ayahCount: 165,
    },
    {
        id: 7,
        name: 'الأعراف',
        makkia: true,
        ayahCount: 206,
    },
    {
        id: 8,
        name: 'الأنفال',
        makkia: false,
        ayahCount: 75,
    },
    {
        id: 9,
        name: 'التوبة',
        makkia: false,
        ayahCount: 129,
    },
    {
        id: 10,
        name: 'يونس',
        makkia: true,
        ayahCount: 109,
    },
    {
        id: 11,
        name: 'هود',
        makkia: true,
        ayahCount: 123,
    },
    {
        id: 12,
        name: 'يوسف',
        makkia: true,
        ayahCount: 111,
    },
    {
        id: 13,
        name: 'الرعد',
        makkia: false,
        ayahCount: 43,
    },
    {
        id: 14,
        name: 'ابراهيم',
        makkia: true,
        ayahCount: 52,
    },
    {
        id: 15,
        name: 'الحجر',
        makkia: true,
        ayahCount: 99,
    },
    {
        id: 16,
        name: 'النحل',
        makkia: true,
        ayahCount: 128,
    },
    {
        id: 17,
        name: 'الإسراء',
        makkia: true,
        ayahCount: 111,
    },
    {
        id: 18,
        name: 'الكهف',
        makkia: true,
        ayahCount: 110,
    },
    {
        id: 19,
        name: 'مريم',
        makkia: true,
        ayahCount: 98,
    },
    {
        id: 20,
        name: 'طه',
        makkia: true,
        ayahCount: 135,
    },
    {
        id: 21,
        name: 'الأنبياء',
        makkia: true,
        ayahCount: 112,
    },
    {
        id: 22,
        name: 'الحج',
        makkia: false,
        ayahCount: 78,
    },
    {
        id: 23,
        name: 'المؤمنون',
        makkia: true,
        ayahCount: 118,
    },
    {
        id: 24,
        name: 'النور',
        makkia: false,
        ayahCount: 64,
    },
    {
        id: 25,
        name: 'الفرقان',
        makkia: true,
        ayahCount: 77,
    },
    {
        id: 26,
        name: 'الشعراء',
        makkia: true,
        ayahCount: 227,
    },
    {
        id: 27,
        name: 'النمل',
        makkia: true,
        ayahCount: 93,
    },
    {
        id: 28,
        name: 'القصص',
        makkia: true,
        ayahCount: 88,
    },
    {
        id: 29,
        name: 'العنكبوت',
        makkia: true,
        ayahCount: 69,
    },
    {
        id: 30,
        name: 'الروم',
        makkia: true,
        ayahCount: 60,
    },
    {
        id: 31,
        name: 'لقمان',
        makkia: true,
        ayahCount: 34,
    },
    {
        id: 32,
        name: 'السجدة',
        makkia: true,
        ayahCount: 30,
    },
    {
        id: 33,
        name: 'الأحزاب',
        makkia: false,
        ayahCount: 73,
    },
    {
        id: 34,
        name: 'سبإ',
        makkia: true,
        ayahCount: 54,
    },
    {
        id: 35,
        name: 'فاطر',
        makkia: true,
        ayahCount: 45,
    },
    {
        id: 36,
        name: 'يس',
        makkia: true,
        ayahCount: 83,
    },
    {
        id: 37,
        name: 'الصافات',
        makkia: true,
        ayahCount: 182,
    },
    {
        id: 38,
        name: 'ص',
        makkia: true,
        ayahCount: 88,
    },
    {
        id: 39,
        name: 'الزمر',
        makkia: true,
        ayahCount: 75,
    },
    {
        id: 40,
        name: 'غافر',
        makkia: true,
        ayahCount: 85,
    },
    {
        id: 41,
        name: 'فصلت',
        makkia: true,
        ayahCount: 54,
    },
    {
        id: 42,
        name: 'الشورى',
        makkia: true,
        ayahCount: 53,
    },
    {
        id: 43,
        name: 'الزخرف',
        makkia: true,
        ayahCount: 89,
    },
    {
        id: 44,
        name: 'الدخان',
        makkia: true,
        ayahCount: 59,
    },
    {
        id: 45,
        name: 'الجاثية',
        makkia: true,
        ayahCount: 37,
    },
    {
        id: 46,
        name: 'الأحقاف',
        makkia: true,
        ayahCount: 35,
    },
    {
        id: 47,
        name: 'محمد',
        makkia: false,
        ayahCount: 38,
    },
    {
        id: 48,
        name: 'الفتح',
        makkia: false,
        ayahCount: 29,
    },
    {
        id: 49,
        name: 'الحجرات',
        makkia: false,
        ayahCount: 18,
    },
    {
        id: 50,
        name: 'ق',
        makkia: true,
        ayahCount: 45,
    },
    {
        id: 51,
        name: 'الذاريات',
        makkia: true,
        ayahCount: 60,
    },
    {
        id: 52,
        name: 'الطور',
        makkia: true,
        ayahCount: 49,
    },
    {
        id: 53,
        name: 'النجم',
        makkia: true,
        ayahCount: 62,
    },
    {
        id: 54,
        name: 'القمر',
        makkia: true,
        ayahCount: 55,
    },
    {
        id: 55,
        name: 'الرحمن',
        makkia: false,
        ayahCount: 78,
    },
    {
        id: 56,
        name: 'الواقعة',
        makkia: true,
        ayahCount: 96,
    },
    {
        id: 57,
        name: 'الحديد',
        makkia: false,
        ayahCount: 29,
    },
    {
        id: 58,
        name: 'المجادلة',
        makkia: false,
        ayahCount: 22,
    },
    {
        id: 59,
        name: 'الحشر',
        makkia: false,
        ayahCount: 24,
    },
    {
        id: 60,
        name: 'الممتحنة',
        makkia: false,
        ayahCount: 13,
    },
    {
        id: 61,
        name: 'الصف',
        makkia: false,
        ayahCount: 14,
    },
    {
        id: 62,
        name: 'الجمعة',
        makkia: false,
        ayahCount: 11,
    },
    {
        id: 63,
        name: 'المنافقون',
        makkia: false,
        ayahCount: 11,
    },
    {
        id: 64,
        name: 'التغابن',
        makkia: false,
        ayahCount: 18,
    },
    {
        id: 65,
        name: 'الطلاق',
        makkia: false,
        ayahCount: 12,
    },
    {
        id: 66,
        name: 'التحريم',
        makkia: false,
        ayahCount: 12,
    },
    {
        id: 67,
        name: 'الملك',
        makkia: true,
        ayahCount: 30,
    },
    {
        id: 68,
        name: 'القلم',
        makkia: true,
        ayahCount: 52,
    },
    {
        id: 69,
        name: 'الحاقة',
        makkia: true,
        ayahCount: 52,
    },
    {
        id: 70,
        name: 'المعارج',
        makkia: true,
        ayahCount: 44,
    },
    {
        id: 71,
        name: 'نوح',
        makkia: true,
        ayahCount: 28,
    },
    {
        id: 72,
        name: 'الجن',
        makkia: true,
        ayahCount: 28,
    },
    {
        id: 73,
        name: 'المزمل',
        makkia: true,
        ayahCount: 20,
    },
    {
        id: 74,
        name: 'المدثر',
        makkia: true,
        ayahCount: 56,
    },
    {
        id: 75,
        name: 'القيامة',
        makkia: true,
        ayahCount: 40,
    },
    {
        id: 76,
        name: 'الانسان',
        makkia: false,
        ayahCount: 31,
    },
    {
        id: 77,
        name: 'المرسلات',
        makkia: true,
        ayahCount: 50,
    },
    {
        id: 78,
        name: 'النبإ',
        makkia: true,
        ayahCount: 40,
    },
    {
        id: 79,
        name: 'النازعات',
        makkia: true,
        ayahCount: 46,
    },
    {
        id: 80,
        name: 'عبس',
        makkia: true,
        ayahCount: 42,
    },
    {
        id: 81,
        name: 'التكوير',
        makkia: true,
        ayahCount: 29,
    },
    {
        id: 82,
        name: 'الإنفطار',
        makkia: true,
        ayahCount: 19,
    },
    {
        id: 83,
        name: 'المطففين',
        makkia: true,
        ayahCount: 36,
    },
    {
        id: 84,
        name: 'الإنشقاق',
        makkia: true,
        ayahCount: 25,
    },
    {
        id: 85,
        name: 'البروج',
        makkia: true,
        ayahCount: 22,
    },
    {
        id: 86,
        name: 'الطارق',
        makkia: true,
        ayahCount: 17,
    },
    {
        id: 87,
        name: 'الأعلى',
        makkia: true,
        ayahCount: 19,
    },
    {
        id: 88,
        name: 'الغاشية',
        makkia: true,
        ayahCount: 26,
    },
    {
        id: 89,
        name: 'الفجر',
        makkia: true,
        ayahCount: 30,
    },
    {
        id: 90,
        name: 'البلد',
        makkia: true,
        ayahCount: 20,
    },
    {
        id: 91,
        name: 'الشمس',
        makkia: true,
        ayahCount: 15,
    },
    {
        id: 92,
        name: 'الليل',
        makkia: true,
        ayahCount: 21,
    },
    {
        id: 93,
        name: 'الضحى',
        makkia: true,
        ayahCount: 11,
    },
    {
        id: 94,
        name: 'الشرح',
        makkia: true,
        ayahCount: 8,
    },
    {
        id: 95,
        name: 'التين',
        makkia: true,
        ayahCount: 8,
    },
    {
        id: 96,
        name: 'العلق',
        makkia: true,
        ayahCount: 19,
    },
    {
        id: 97,
        name: 'القدر',
        makkia: true,
        ayahCount: 5,
    },
    {
        id: 98,
        name: 'البينة',
        makkia: false,
        ayahCount: 8,
    },
    {
        id: 99,
        name: 'الزلزلة',
        makkia: false,
        ayahCount: 8,
    },
    {
        id: 100,
        name: 'العاديات',
        makkia: true,
        ayahCount: 11,
    },
    {
        id: 101,
        name: 'القارعة',
        makkia: true,
        ayahCount: 11,
    },
    {
        id: 102,
        name: 'التكاثر',
        makkia: true,
        ayahCount: 8,
    },
    {
        id: 103,
        name: 'العصر',
        makkia: true,
        ayahCount: 3,
    },
    {
        id: 104,
        name: 'الهمزة',
        makkia: true,
        ayahCount: 9,
    },
    {
        id: 105,
        name: 'الفيل',
        makkia: true,
        ayahCount: 5,
    },
    {
        id: 106,
        name: 'قريش',
        makkia: true,
        ayahCount: 4,
    },
    {
        id: 107,
        name: 'الماعون',
        makkia: true,
        ayahCount: 7,
    },
    {
        id: 108,
        name: 'الكوثر',
        makkia: true,
        ayahCount: 3,
    },
    {
        id: 109,
        name: 'الكافرون',
        makkia: true,
        ayahCount: 6,
    },
    {
        id: 110,
        name: 'النصر',
        makkia: false,
        ayahCount: 3,
    },
    {
        id: 111,
        name: 'المسد',
        makkia: true,
        ayahCount: 5,
    },
    {
        id: 112,
        name: 'الإخلاص',
        makkia: true,
        ayahCount: 4,
    },
    {
        id: 113,
        name: 'الفلق',
        makkia: true,
        ayahCount: 5,
    },
    {
        id: 114,
        name: 'الناس',
        makkia: true,
        ayahCount: 6,
    },
] as const;

export function absoluteAyaNumber(surah: number, aya: number): number {
    return SURAH_METADATA.slice(0, surah - 1).reduce((total, item) => total + item.ayahCount, 0) + aya;
}
